// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVwy9AvgJsMryr-oILCndXslKv2A16vKw',
    appId: '1:105456248073:web:c8bbdea3702491b9739fd8',
    messagingSenderId: '105456248073',
    projectId: 'calenbridge',
    authDomain: 'calenbridge.firebaseapp.com',
    storageBucket: 'calenbridge.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXkjT0ZyiG8QsQzo23HnshdabP0vjWqHE',
    appId: '1:105456248073:android:ff62f61ce2ccbab9739fd8',
    messagingSenderId: '105456248073',
    projectId: 'calenbridge',
    storageBucket: 'calenbridge.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAftTJcUlFMd4MUlmBEY5srucKrpDBheDs',
    appId: '1:105456248073:ios:b42ec385f2eb6a29739fd8',
    messagingSenderId: '105456248073',
    projectId: 'calenbridge',
    storageBucket: 'calenbridge.firebasestorage.app',
    iosBundleId: 'com.example.calenbridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAftTJcUlFMd4MUlmBEY5srucKrpDBheDs',
    appId: '1:105456248073:ios:b42ec385f2eb6a29739fd8',
    messagingSenderId: '105456248073',
    projectId: 'calenbridge',
    storageBucket: 'calenbridge.firebasestorage.app',
    iosBundleId: 'com.example.calenbridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVwy9AvgJsMryr-oILCndXslKv2A16vKw',
    appId: '1:105456248073:web:e6c5c418deb3d0ce739fd8',
    messagingSenderId: '105456248073',
    projectId: 'calenbridge',
    authDomain: 'calenbridge.firebaseapp.com',
    storageBucket: 'calenbridge.firebasestorage.app',
  );
}
